kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: rust:1
  commands:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - rustup component add clippy
  - cargo clippy -- -Dwarnings
