[package]
name = "update_dns_record"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
http = "1.1"
local-ip-address = "0.6"
nix = { version = "0.29", features = ["fs"] }
# workaround for crosscompile
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
syslog = "6.1.0"

[dev-dependencies]
mockall = "0.12"
test-context = "0.3"

[profile.dev]
debug = true
opt-level = 0

[profile.release]
opt-level = "z"
debug = false
lto = true
overflow-checks = true
codegen-units = 1
panic = "abort"
strip = true
