[package]
name = "update_dns_record"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive", "env"] }
local-ip-address = "0.6.1"
# workaround for crosscompile
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.114" }

[dev-dependencies]
mockall = "0.12.1"
mockito = "1.3.0"

[profile.release]
opt-level = "z"
debug = false
lto = true
overflow-checks = true
codegen-units = 1
panic = "abort"
strip = true
